version: '3.9'

services:
  backend:
    build: .
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: mongodb://mongo:27017/portfolio
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    env_file:
      - .env.local
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: portfolio
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongo-data:
